swagger: '2.0'
info:
  description: 'Management api for Hercules. Uses for create, midify, delete streams and timelines'
  version: 0.1.0
  title: Hercules management API
host: 'vstk-airgate:6307'
tags: []
schemes:
  - http
paths:
  /ping:
    get:
      tags: []
      summary: Ping
      description: Check server status
      operationId: Ping
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          $ref: '#/responses/success'
  /streams/create:
    post:
      tags:
        - stream
      summary: Create stream
      description: Create stream
      operationId: createStream
      produces:
        - plain/text
      parameters:
        - $ref: '#/parameters/apiKey'
        - name: body
          in: body
          description: CreateStreamRequest
          schema:
            $ref: '#/definitions/createStreamRequest'
      responses:
        '200':
          $ref: '#/responses/success'
        '400':
          $ref: '#/responses/badRequest'
        '401':
          $ref: '#/responses/managementRulesIsAbsent'
        '403':
          $ref: '#/responses/forbidden'
        '404':
          $ref: '#/responses/notFound'
        '409':
          $ref: '#/responses/conflict'
  /streams/delete:
    post:
      tags:
        - stream
      summary: Delete stream
      description: Delete stream
      operationId: deleteStream
      produces:
        - plain/text
      parameters:
        - $ref: '#/parameters/apiKey'
        - name: stream
          in: query
          description: Название стрима
          required: true
          type: string
          pattern: '[a-z0-9_]{1,48}'
      responses:
        '200':
          $ref: '#/responses/success'
        '400':
          $ref: '#/responses/badRequest'
        '401':
          $ref: '#/responses/managementRulesIsAbsent'
        '403':
          $ref: '#/responses/forbidden'
        '404':
          $ref: '#/responses/notFound'
  /streams/list:
    get:
      tags:
        - stream
      summary: List streams
      description: List streams
      operationId: listStreams
      produces:
        - plain/text
      parameters:
        - $ref: '#/parameters/apiKey'
      responses:
        '200':
          $ref: '#/responses/success'
        '401':
          $ref: '#/responses/unauthorized'
  /timelines/create:
    post:
      tags:
        - timeline
      summary: Create timeline
      description: Create timeline
      operationId: createTimeline
      produces:
        - plain/text
      parameters:
        - $ref: '#/parameters/apiKey'
        - name: body
          in: body
          description: CreateTimelineRequest
          schema:
            $ref: '#/definitions/createTimelineRequest'
      responses:
        '200':
          $ref: '#/responses/success'
        '400':
          $ref: '#/responses/badRequest'
        '401':
          $ref: '#/responses/managementRulesIsAbsent'
        '403':
          $ref: '#/responses/forbidden'
        '404':
          $ref: '#/responses/notFound'
        '409':
          $ref: '#/responses/conflict'
  /timelines/delete:
    post:
      tags:
        - timeline
      summary: Delete timeline
      description: Delete timeline
      operationId: deleteTimeline
      produces:
        - plain/text
      parameters:
        - $ref: '#/parameters/apiKey'
        - name: stream
          in: query
          description: Timeline name
          required: true
          type: string
          pattern: '[a-z0-9_]{1,48}'
      responses:
        '200':
          $ref: '#/responses/success'
        '400':
          $ref: '#/responses/badRequest'
        '401':
          $ref: '#/responses/managementRulesIsAbsent'
        '403':
          $ref: '#/responses/forbidden'
        '404':
          $ref: '#/responses/notFound'
  /timelines/list:
    get:
      tags:
        - timeline
      summary: List timelines
      description: List timelines
      operationId: listTimelines
      produces:
        - plain/text
      parameters:
        - $ref: '#/parameters/apiKey'
      responses:
        '200':
          $ref: '#/responses/success'
        '401':
          $ref: '#/responses/unauthorized'        
  /rules/set:
    post:
      tags:
        - rules
      summary: Set rules
      description: Set rules
      operationId: setRules
      produces:
        - plain/text
      parameters:
        - $ref: '#/parameters/apiKey'
        - name: key
          in: query
          description: API key for which rule is set
          required: true
          type: string
          pattern: '[a-zA-Z0-9_\-]+'
        - name: pattern
          in: query
          description: Pattern for stream or timelime names
          required: true
          type: string
          pattern: '[a-z0-9_\*\?]+'
          example: proj_name_*
        - name: rights
          in: query
          description: Combination of read, write and modified rights
          required: true
          type: string
          enum: 
            - '---'
            - 'r--'
            - '-w-'
            - '--m'
            - 'rw-'
            - 'r-m'
            - '-wm'
            - 'rwm'
      responses:
        '200':
          $ref: '#/responses/success'
        '400':
          $ref: '#/responses/badRequest'
        '401':
          $ref: '#/responses/unauthorized'
        '403':
          $ref: '#/responses/forbidden'
        '404':
          $ref: '#/responses/notFound'
        '409':
          $ref: '#/responses/conflict'
  /rules/list:
    get:
      tags:
        - rules
      summary: List rules
      description: List rules
      operationId: listRules
      produces:
        - plain/text
      parameters:
        - $ref: '#/parameters/apiKey'
      responses:
        '200':
          $ref: '#/responses/success'
        '400':
          $ref: '#/responses/badRequest'
        '401':
          $ref: '#/responses/unauthorized'        
  /blacklist/add:
    post:
      tags:
        - blacklist
      summary: Add apiKey to blacklist
      description: Add apiKey to blacklist
      operationId: addApiKeyToBlacklist
      produces:
        - plain/text
      parameters:
        - $ref: '#/parameters/apiKey'
        - name: body
          in: body
          description: need to add
          schema:
            type: string
      responses:
        '200':
          $ref: '#/responses/success'
        '400':
          $ref: '#/responses/badRequest'
        '401':
          $ref: '#/responses/unauthorized'
        '403':
          $ref: '#/responses/forbidden'
        '404':
          $ref: '#/responses/notFound'
        '409':
          $ref: '#/responses/conflict'
  /blacklist/remove:
    post:
      tags:
        - blacklist
      summary: Remove apiKey from blacklist
      description: Remove apiKey from blacklist
      operationId: removeApiKeyFromBlacklist
      produces:
        - plain/text
      parameters:
        - $ref: '#/parameters/apiKey'
        - name: body
          in: body
          description: need to add
          schema:
            type: string
      responses:
        '200':
          $ref: '#/responses/success'
        '400':
          $ref: '#/responses/badRequest'
        '401':
          $ref: '#/responses/unauthorized'
  /blacklist/list:
    get:
      tags:
        - blacklist
      summary: List blacklist
      description: List blacklist
      operationId: listBlacklist
      produces:
        - plain/text
      parameters:
        - $ref: '#/parameters/apiKey'
      responses:
        '200':
          $ref: '#/responses/success'
        '401':
          $ref: '#/responses/unauthorized'        
definitions:
  #$ref: './definitions.yaml'
  createStreamRequest:
    type: object
    properties:
      type:
        type: string
        description: stream type
        enum:
          - base
          - derived
      name:
        type: string
      partitions:
        type: integer
      shardingKey:
        type: array
        description: Если то то то
        items:
          type: string
      ttl:
        type: integer
      sources:
        type: string
      filters:
        type: string
    example:
      type: base
      name: msl_teststream_2
      partitions: 1
      shardingKey: []
      ttl: 100500
  createTimelineRequest:
    type: object
    properties:
      name:
        type: string
      slices:
        type: string
      shardingKey:
        description: todo
        type: array
        items:
          type: string
      ttl:
        type: integer
      timetrapSize:
        type: integer
      sources:
        type: string
      filters:
        type: string
parameters:
  apiKey:
    name: apiKey
    in: header
    type: string
    pattern: '^\d{3}-\d{2}-\d{4}$'
    required: true
    description: API key for authorization
responses:
  unauthorized:
    description: Unauthorized
    schema:
      type: string
      example: Unauthorized error text
  managementRulesIsAbsent:
    description: Management rules for this apiKey is absent
  badRequest:
    description: Bad request
    schema:
      type: string
      example: Bad request error text
  forbidden:
    description: Forbidden
    schema:
      type: string
      example: Forbidden error text
  notFound: 
    description: Not Found
    schema:
      type: string
      example: Not Found error text
  conflict:    
    description: Conflict
    schema:
      type: string
      example: Conflict error text
  success:
    description: successful operation
    schema:
      type: string
      example: OK
