swagger: '2.0'
info:
  description: 'Stream api for Hercules. Uses for get info from streams'
  version: 0.1.0
  title: Hercules stream API
host: 'vstk-airgate:6308'
tags: []
schemes:
  - http
paths:
  /ping:
    get:
      tags: []
      summary: Ping
      description: Check server status
      operationId: Ping
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          $ref: '#/responses/success'
  /stream/read:
    post:
      tags: [stream]
      summary:
definitions:
  #$ref: './definitions.yaml'
  createStreamRequest:
    type: object
    properties:
      type:
        type: string
        description: stream type
        enum:
          - base
          - derived
      name:
        type: string
      partitions:
        type: integer
      shardingKey:
        type: array
        description: Если то то то
        items:
          type: string
      ttl:
        type: integer
      sources:
        type: string
      filters:
        type: string
    example:
      type: base
      name: msl_teststream_2
      partitions: 1
      shardingKey: []
      ttl: 100500
parameters:
  apiKey:
    name: apiKey
    in: header
    type: string
    pattern: '^\d{3}-\d{2}-\d{4}$'
    required: true
    description: API key for authorization
responses:
  unauthorized:
    description: Unauthorized
    schema:
      type: string
      example: Unauthorized error text
  managementRulesIsAbsent:
    description: Management rules for this apiKey is absent
  badRequest:
    description: Bad request
    schema:
      type: string
      example: Bad request error text
  forbidden:
    description: Forbidden
    schema:
      type: string
      example: Forbidden error text
  notFound: 
    description: Not Found
    schema:
      type: string
      example: Not Found error text
  conflict:    
    description: Conflict
    schema:
      type: string
      example: Conflict error text
  success:
    description: successful operation
    schema:
      type: string
      example: OK
